Removed old hyprlang.

diff --git a/Configs/.local/bin/hyde-shell b/Configs/.local/bin/hyde-shell
--- a/Configs/.local/bin/hyde-shell
+++ b/Configs/.local/bin/hyde-shell
@@ -5,7 +5,6 @@
 # shellcheck disable=SC2086
 # shellcheck disable=SC1090
 
-
 python_initialized() {
 
 	local python_script="${LIB_DIR}/hyde/pyutils/python_env.py"
@@ -24,7 +23,6 @@ python_initialized() {
 	python3 "${python_script}" create >/dev/null 2>&1 && return 0
 	echo "Create failed; attempting rebuild..."
 	python3 "${python_script}" rebuild
-
 }
 
 python_activate() {
@@ -42,11 +40,10 @@ python_activate() {
 }
 
 lua_initialized() {
-python_activate
-python3 "${LIB_DIR}/hyde/pyutils/lua_env.py" sync || \
-python3 "${LIB_DIR}/hyde/pyutils/lua_env.py" rebuild
+	python_activate
+	python3 "${LIB_DIR}/hyde/pyutils/lua_env.py" sync ||
+		python3 "${LIB_DIR}/hyde/pyutils/lua_env.py" rebuild
 }
-
 
 initialized() {
 	cat <<EOF
@@ -436,20 +433,34 @@ run_command() {
 		[[ -d "$dir" ]] && SCRIPT_DIRS+=("$dir")
 	done
 
+	local l_env="${XDG_STATE_HOME:-$HOME/.local/state}/hyde/lua_env"
+
 	# Try to find and execute the command in priority order
 	for dir in "${SCRIPT_DIRS[@]}"; do
+
+		if
+			[[ -f "$dir/${1}.lua" ]] &&
+				[[ -d "${l_env}/lib/lua" ]] &&
+				[[ -d "${l_env}/lib/luarocks" ]] &&
+				[[ -d "${l_env}/share/lua" ]]
+		then
+			# echo "Executing Lua script: $dir/${1}.lua"
+			exec lua "$dir/${1}.lua" "${@:2}"
+			exit 0
+		fi
+
 		# Try .sh extension first
 		if [[ -f "$dir/${1}.sh" ]]; then
 			exec bash "$dir/${1}.sh" "${@:2}"
 		# Try .lua extension second
-		elif [[ -f "$dir/${1}.lua" 	]]; then
+		elif [[ -f "$dir/${1}.lua" ]]; then
 			lua_runtime="${XDG_STATE_HOME:-$HOME/.local/state}/hyde/lua_env/bin/lua"
 			activate_script="${XDG_STATE_HOME:-$HOME/.local/state}/hyde/lua_env/bin/activate_posix"
 			if [[ -f "$activate_script" ]] && [[ -x "$lua_runtime" ]]; then
-			source "$activate_script"
+				source "$activate_script"
 			else
-			# I hate automating this as building the environment is slow and should be optional for now.
-			# Calling for lua gods to speed up the process 🙏
+				# I hate automating this as building the environment is slow and should be optional for now.
+				# Calling for lua gods to speed up the process 🙏
 				print_log -warn "Lua environment not found!" " Please run 'hyde-shell luainit' to set up the environment."
 				send_notifs "Lua environment not found!" "Please run 'hyde-shell luainit' to set up the environment."
 				exit 1
@@ -499,16 +510,14 @@ run_uv() {
 	esac
 }
 
-# Run luarocks inside the LuaJIT environment
 run_luarocks() {
 	shift
-	local luarocks_bin="${XDG_STATE_HOME:-$HOME/.local/state}/hyde/lua_env/bin/luarocks"
-	if [[ -x "$luarocks_bin" ]]; then
-		source ${XDG_STATE_HOME:-$HOME/.local/state}/hyde/lua_env/bin/activate_posix
-		"$luarocks_bin" "$@"
+	local lua_env_dir="${XDG_STATE_HOME:-$HOME/.local/state}/hyde/lua_env"
+	if command -v luarocks >/dev/null 2>&1; then
+		luarocks --tree "${lua_env_dir}" "$@"
 	else
-		echo "luarocks not found in LuaJIT environment."
-		echo "You may need to run 'python ${LIB_DIR}/hyde/lua_env.py rebuild' to set up the environment."
+		echo "luarocks not found in your system."
+		echo "You may need to install 'luarocks' and 'lua''"
 	fi
 }
 
@@ -526,12 +535,12 @@ run_pypr() {
 		fi
 
 		if [[ -S "$socket_path" ]] && pgrep -u "$USER" pypr >/dev/null 2>&1; then
-			local -a msg=("$@")
-			((${#msg[@]} == 0)) && msg=("help")
-			if ! printf '%s\n' "${msg[*]}" | nc -N -U "$socket_path" 2>/dev/null; then #! openbsd netcat only
-				if ! printf '%s\n' "${msg[*]}" | socat - UNIX-CONNECT:"$socket_path" 2>/dev/null; then
-					if ! printf '%s\n' "${msg[*]}" | ncat -U "$socket_path" 2>/dev/null; then
-						if ! pypr "${msg[@]}"; then
+			message="${*:-"help"}"
+			# Send the message to the socket and print the response
+			if ! printf "%s" "${message[@]}" | nc -N -U "$socket_path" 2>/dev/null; then #! openbsd netcat only
+				if ! printf "%s" "${message[@]}" | socat - UNIX-CONNECT:"$socket_path" 2>/dev/null; then
+					if ! printf "%s" "${message[@]}" | ncat -U "$socket_path" 2>/dev/null; then
+						if ! pypr "${message[@]}"; then
 							print_log -sec "pypr" "Error communicating with socket: $socket_path"
 							exit 1
 						fi
@@ -674,7 +683,6 @@ SHARE_DIR=$(realpath "${BIN_DIR}/../share")
 PATH="${XDG_CONFIG_HOME:-$HOME/.config}/hyde/scripts:$BIN_DIR:$LIB_DIR/hyde:$PATH" #! I added this to the PATH to make sure that the hyde commands are available in the shell
 # Define hyde scripts search paths (colon-separated, user configurable)
 HYDE_SCRIPTS_PATH="${HYDE_SCRIPTS_PATH:-${XDG_CONFIG_HOME:-$HOME/.config}/hyde/scripts:${LIB_DIR}/hyde}:${XDG_DATA_HOME:-$HOME/.local/share}/waybar/scripts:${XDG_CONFIG_HOME:-$HOME/.config}/waybar/scripts"
-
 export BIN_DIR LIB_DIR SHARE_DIR PATH HYDE_SCRIPTS_PATH
 
 #*--------------------------------------------------------------------------------
